export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const FETCH_VEHICLES_START = 'FETCH_VEHICLES_START';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_FAIL = 'FETCH_VEHICLES_FAIL';
export const GET_VEHICLE_INFO = 'GET_VEHICLE_INFO';
export const GET_VEHICLE_INFO_START = 'GET_VEHICLE_INFO_START'
export const GET_VEHICLE_INFO_SUCCESS = 'GET_VEHICLE_INFO_SUCCESS'
export const GET_VEHICLE_INFO_FAIL = 'GET_VEHICLE_INFO_FAIL';
