export const FETCH_FILMS = 'FETCH_FILMS';
export const FETCH_FILMS_START = 'FETCH_FILMS_START';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAIL = 'FETCH_FILMS_FAIL';
export const GET_FILM_INFO = 'GET_FILM_INFO';
export const GET_FILM_INFO_START = 'GET_FILM_INFO_START'
export const GET_FILM_INFO_SUCCESS = 'GET_FILM_INFO_SUCCESS'
export const GET_FILM_INFO_FAIL = 'GET_FILM_INFO_FAIL';
