export const FETCH_PLANETS = 'FETCH_PLANETS';
export const FETCH_PLANETS_START = 'FETCH_PLANETS_START';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAIL = 'FETCH_PLANETS_FAIL';
export const GET_PLANET_INFO = 'GET_PLANET_INFO';
export const GET_PLANET_INFO_START = 'GET_PLANET_INFO_START'
export const GET_PLANET_INFO_SUCCESS = 'GET_PLANET_INFO_SUCCESS'
export const GET_PLANET_INFO_FAIL = 'GET_PLANET_INFO_FAIL';
